name: Nano Linux Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential wget cpio python3 unzip rsync bc libncurses-dev libelf-dev libssl-dev bison flex xorriso mtools libisoburn-dev genisoimage mtools gettext texinfo libwayland-dev libxkbcommon-dev libpixman-1-dev libgbm-dev
        
      - name: Build
        run: |
          cd buildroot
          git clone --depth 1 --branch 2024.02 https://github.com/buildroot/buildroot.git .
          cp ../nano_defconfig configs/nano_defconfig
          
          # 1. Применяем конфиг
          make nano_defconfig
          
          # 2. ПРИНУДИТЕЛЬНО ВКЛЮЧАЕМ нужные нам форматы образов прямо в .config
          # (Это работает надежнее, чем echo до make)
          sed -i 's/.*BR2_TARGET_ROOTFS_ISO9660.*/BR2_TARGET_ROOTFS_ISO9660=y/' .config
          sed -i 's/.*BR2_TARGET_ROOTFS_EXT2.*/BR2_TARGET_ROOTFS_EXT2=y/' .config
          
          # 3. Важно: пересобираем конфиг с новыми настройками
          make olddefconfig
          
          # 4. Проверка (чтобы увидеть в логах, включились ли они)
          echo "Checking config..."
          grep "BR2_TARGET_ROOTFS_ISO9660" .config
          
          # 5. Сборка
          make
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: nano-os
          path: buildroot/output/images/*
