name: Nano Linux Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential wget cpio python3 unzip rsync bc libncurses-dev libelf-dev libssl-dev bison flex xorriso mtools libisoburn-dev gettext texinfo libwayland-dev libxkbcommon-dev libpixman-1-dev libgbm-dev
        
      - name: Build
        run: |
          rm -rf buildroot
          git clone --depth 1 --branch 2024.02 https://github.com/buildroot/buildroot.git
          
          rm -f build.log
          
          # set -e: останавливает скрипт при первой же ошибке
          # set -x: выводит все команды перед их выполнением (увидишь, где именно затык)
          set -ex
          
          echo "BR2_ROOTFS_OVERLAY=\"${GITHUB_WORKSPACE}/board/nano_linux/rootfs-overlay\"" >> .config
          
          # Собираем с дебагом
          make V=1 2>&1 | tee build.log

      - name: Diagnostic Output
        if: steps.build_step.outcome != 'success'
        run: |
          echo "--- БИЛД УПАЛ! Вывод последних 100 строк ---"
          tail -n 100 buildroot/build.log
          
          echo "--- ПРОВЕРКА МЕСТА НА ДИСКЕ ---"
          df -h
          
          echo "--- ПРОВЕРКА ПАМЯТИ ---"
          free -m
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: nano-os-images
          path: buildroot/output/images/*
